### ISSUE TITLE
Provide a secure GItOps Way to provide the token

### ISSUE THREAD

**Issue by rowi1de** [traefik/hub-helm-chart#64]
Currently it's not possible to commit the Chart + Configuration in a GitOps way, was the Token is part of the values and not referenced from a secret.

Example for ArgoCD
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-hub
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade on delete
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: traefik-hub
  source:
    repoURL: 'https://helm.traefik.io/hub'
    chart: hub-agent
    targetRevision:  1.0.0
    helm:
      values: |
        token: "plop"
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-hub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
