### ISSUE TITLE
hub-agent-dev-portal pod in status  CrashLoopBackOff with error msg "listen tcp :80: bind: permission denied" / "Unable to listen and serve dev portal requests"

### ISSUE THREAD

**Issue by nifr** [traefik/hub-helm-chart#83]
## Kubernetes Setup

* Debian Bullseye `11.6`
* k0s `v1.25.7`
* containerd

## Issue

By default ports <1000 can not be exposed by containers running as non-root users on containerd.

I experience the same permission issues with `hub-agent-dev-portal` that are described for the traefik Chart in [this issue](https://github.com/traefik/traefik-helm-chart/issues/336#issuecomment-776163841).

```bash
kubectl -n traefik get pods
```

```
NAME                                     READY   STATUS             RESTARTS         AGE
hub-agent-auth-server-5bd76d8c79-zbkcl   1/1     Running            0                39m
hub-agent-controller-6448fdb84b-bcm7s    1/1     Running            3 (9m30s ago)    39m
hub-agent-dev-portal-6f4c896c89-tbmt6    0/1     CrashLoopBackOff   12 (2m41s ago)   39m
hub-agent-tunnel-7b684d666b-qp8hr        1/1     Running            0                39m
traefik-6f6596fb44-pn6qd                 1/1     Running            0                47m
```

If I inspect the logs ...

```bash
kubectl -n traefik logs svc/hub-agent-dev-portal
```

Output:

```json
{
  "level":"error",
  "error":"listen tcp :80: bind: permission denied",
  "time":1679946580,
  "caller":"github.com/traefik/hub-agent-kubernetes/cmd/agent/dev_portal.go:149",
  "message":"Unable to listen and serve dev portal requests"
}
{
  "level":"fatal",
  "error":"dev portal stopped",
  "time":1679946580,
  "caller":"github.com/traefik/hub-agent-kubernetes/cmd/agent/main.go:41",
  "message":"Error while executing command"
}
```

There's currently no way to override the `securityContext` in the Helm chart's `values.yaml`.

If I override the `securityContext` in [deployment-dev-portal.yaml](https://github.com/traefik/hub-helm-chart/blob/e29d5958e9664d851cf0a94a80493bfc4bf5c6bc/hub-agent/templates/deployment-dev-portal.yaml#L66) as follows:

```
# [..]
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: true
            runAsNonRoot: false
            runAsUser: 0
            runAsGroup: 0
            seccompProfile:
              type: RuntimeDefault
 ```

... the chart can be deployed successfully.

```
NAME                                     READY   STATUS    RESTARTS        AGE
hub-agent-auth-server-5bd76d8c79-zbkcl   1/1     Running   0               63m
hub-agent-controller-6448fdb84b-bcm7s    1/1     Running   6 (3m40s ago)   63m
hub-agent-dev-portal-5776ddfdf9-z29hk    1/1     Running   0               32s
hub-agent-tunnel-7b684d666b-qp8hr        1/1     Running   0               63m
traefik-6f6596fb44-pn6qd                 1/1     Running   0               71m
```

---

A possible solution is to provide an option to overide the `securityContext` with `.Values.devPortalDeployment.securityContext`.

This is possible with the `traefik` Helm Chart [here](https://github.com/traefik/traefik-helm-chart/blob/24cf0ee00338970ab7f3cae03eaf2edb451632f7/traefik/values.yaml#L853).
